FROM node:lts AS builder

WORKDIR /app/webui

RUN corepack enable

COPY webui/ .

RUN yarn install

RUN yarn run build-prod

FROM nginx:stable

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/webui/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/wasa.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
