FROM golang:1.21 AS builder

WORKDIR /src/

ENV CGO_ENABLED=1

COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm

RUN apt-get update && apt-get install -y sqlite3 ca-certificates && rm -rf /var/lib/apt/lists/*

EXPOSE 3000 4000

WORKDIR /app/

COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
